# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux
addons:
  apt:
    packages:
      - libv8-dev
r_github_packages:
  - ropensci/jsonvalidate
  - mrc-ide/odin.js
after_success:
  - Rscript -e 'covr::codecov()'
